# Pandas Basics Notebook

#### 1.What is pandas?

**Definition**: pandas is python lib used for data cleaning ,analysis and manipulation.

- works like excel bit faster
- helps load, clean, filter, analyze data
- uses:data science ,machine learning, finance, analytics, and automating data task.

# import pandas

In [2]:
import pandas as pd

In [3]:
import numpy as np

### Pandas data structures

**Series**-> One dimensional column

**Dataframe**->tab;le with rows +columns

In [4]:
o=pd.Series([10,20,30])
o

0    10
1    20
2    30
dtype: int64

In [5]:
df=pd.DataFrame({
    "name":["Uma","Renuka"],
    "age":[32,65]
})
df

     name  age
0     Uma   32
1  Renuka   65

In [6]:
data={
    "domain":["AI","ML","DS"],
    "trainer_name":["pavan","mani","harsha"],
}
data

{'domain': ['AI', 'ML', 'DS'], 'trainer_name': ['pavan', 'mani', 'harsha']}

In [7]:
df=pd.DataFrame(data)
df

  domain trainer_name
0     AI        pavan
1     ML         mani
2     DS       harsha

# Reading Data(csv)

In [8]:
df=pd.read_csv(r"C:\Users\harsh\Downloads\cleaned_car_price_dataset.csv")
df

,Car_Name,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Selling_Price
0,Car_0,2011,14.91,66476,Petrol,Dealer,Manual,1,7.16
1,Car_1,2019,17.39,49811,Diesel,Individual,Automatic,2,9.98
2,Car_2,2015,17.56,76180,Petrol,Dealer,Manual,0,9.09
3,Car_3,2012,9.88,117856,CNG,Dealer,Automatic,2,3.76
4,Car_4,2011,18.09,73450,Diesel,Dealer,Manual,0,9.49
...,...,...,...,...,...,...,...,...,...
195,Car_195,2009,15.44,11949,Diesel,Individual,Manual,2,6.82
196,Car_196,2009,5.17,60393,Diesel,Individual,Manual,0,1.07
197,Car_197,2013,7.25,143013,Petrol,Individual,Automatic,2,1.68
198,Car_198,2013,12.87,30934,Diesel,Individual,Automatic,1,6.01
199,Car_199,2007,17.74,80745,CNG,Individual,Manual,2,8.20

In [9]:
df=pd.read_csv(r"C:\Users\harsh\Downloads\weather_dataset_2025.csv")
df

,Date,City,Temperature_C,Humidity_%,Wind_Speed_km_h,Precipitation_mm,Condition
0,2025-01-01,Riyadh,15.8,94,21.0,0.00,Cloudy
1,2025-01-01,Jeddah,31.5,54,25.3,3.71,Windy
2,2025-01-01,Dammam,30.4,33,8.6,3.14,Partly Cloudy
3,2025-01-01,Dubai,34.0,37,18.7,0.00,Foggy
4,2025-01-01,Doha,28.3,32,6.8,0.00,Rainy
...,...,...,...,...,...,...,...
5470,2025-12-31,Sydney,33.5,71,22.9,4.88,Sunny
5471,2025-12-31,Toronto,9.1,43,37.4,5.03,Sunny
5472,2025-12-31,Berlin,6.3,42,23.7,10.68,Windy
5473,2025-12-31,Mumbai,27.6,58,12.5,3.23,Cloudy
5474,2025-12-31,Singapore,44.3,75,4.6,0.00,Stormy

# Reading data(Excel)

In [10]:
df=pd.read_excel(r"C:\Users\harsh\Downloads\weather_dataset_kaggle.xlsx")
df

,Date,City,Temperature_C,Humidity_%,WindSpeed_kmh,Rainfall_mm,Pressure_hPa,Weather_Condition,UV_Index
0,2025-01-02,Abuja,35.9,97,8.7,29.6,1028,Rainy,4
1,2025-01-03,Abuja,27.0,49,23.6,5.0,992,Sunny,3
2,2025-01-04,Abuja,18.6,46,20.6,116.1,1003,Stormy,10
3,2025-01-05,Kano,27.7,83,32.6,100.7,996,Cloudy,11
4,2025-01-06,Lagos,23.7,87,28.8,56.8,1026,Windy,4
...,...,...,...,...,...,...,...,...,...
495,2026-05-12,Kano,33.9,62,16.0,78.6,1017,Stormy,11
496,2026-05-13,Lagos,19.3,94,2.3,112.6,998,Windy,5
497,2026-05-14,Abuja,29.4,87,20.6,120.0,1023,Windy,6
498,2026-05-15,Kano,31.4,71,14.6,85.4,1017,Windy,1
499,2026-05-16,Lagos,23.8,90,12.9,101.8,987,Sunny,9

# Writting the data into files

In [11]:
df.to_csv('data.csv',index=False)

In [ ]:
df.to_excel('new.xlsx', sheet_nmae='weather_data',index=False)

## Exploring data

In [16]:
df.head()

,Date,City,Temperature_C,Humidity_%,WindSpeed_kmh,Rainfall_mm,Pressure_hPa,Weather_Condition,UV_Index
0,2025-01-02,Abuja,35.9,97,8.7,29.6,1028,Rainy,4
1,2025-01-03,Abuja,27.0,49,23.6,5.0,992,Sunny,3
2,2025-01-04,Abuja,18.6,46,20.6,116.1,1003,Stormy,10
3,2025-01-05,Kano,27.7,83,32.6,100.7,996,Cloudy,11
4,2025-01-06,Lagos,23.7,87,28.8,56.8,1026,Windy,4

In [17]:
df.head(2)

,Date,City,Temperature_C,Humidity_%,WindSpeed_kmh,Rainfall_mm,Pressure_hPa,Weather_Condition,UV_Index
0,2025-01-02,Abuja,35.9,97,8.7,29.6,1028,Rainy,4
1,2025-01-03,Abuja,27.0,49,23.6,5.0,992,Sunny,3

In [18]:
df.tail()

,Date,City,Temperature_C,Humidity_%,WindSpeed_kmh,Rainfall_mm,Pressure_hPa,Weather_Condition,UV_Index
495,2026-05-12,Kano,33.9,62,16.0,78.6,1017,Stormy,11
496,2026-05-13,Lagos,19.3,94,2.3,112.6,998,Windy,5
497,2026-05-14,Abuja,29.4,87,20.6,120.0,1023,Windy,6
498,2026-05-15,Kano,31.4,71,14.6,85.4,1017,Windy,1
499,2026-05-16,Lagos,23.8,90,12.9,101.8,987,Sunny,9

In [19]:
df.tail(3)

,Date,City,Temperature_C,Humidity_%,WindSpeed_kmh,Rainfall_mm,Pressure_hPa,Weather_Condition,UV_Index
497,2026-05-14,Abuja,29.4,87,20.6,120.0,1023,Windy,6
498,2026-05-15,Kano,31.4,71,14.6,85.4,1017,Windy,1
499,2026-05-16,Lagos,23.8,90,12.9,101.8,987,Sunny,9

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               500 non-null    str
 1   City               500 non-null    str
 2   Temperature_C      500 non-null    float64
 3   Humidity_%         500 non-null    int64
 4   WindSpeed_kmh      500 non-null    float64
 5   Rainfall_mm        500 non-null    float64
 6   Pressure_hPa       500 non-null    int64
 7   Weather_Condition  500 non-null    str
 8   UV_Index           500 non-null    int64
dtypes: float64(3), int64(3), str(3)
memory usage: 35.3 KB

In [21]:
df['Date']

0      2025-01-02
1      2025-01-03
2      2025-01-04
3      2025-01-05
4      2025-01-06
          ...
495    2026-05-12
496    2026-05-13
497    2026-05-14
498    2026-05-15
499    2026-05-16
Name: Date, Length: 500, dtype: str

In [22]:
df.Date

0      2025-01-02
1      2025-01-03
2      2025-01-04
3      2025-01-05
4      2025-01-06
          ...
495    2026-05-12
496    2026-05-13
497    2026-05-14
498    2026-05-15
499    2026-05-16
Name: Date, Length: 500, dtype: str

In [24]:
df['Date'][df['Weather_Condition']=='Rainy']

0      2025-01-02
5      2025-01-07
10     2025-01-12
19     2025-01-21
27     2025-01-29
          ...
440    2026-03-18
445    2026-03-23
459    2026-04-06
479    2026-04-26
490    2026-05-07
Name: Date, Length: 95, dtype: str

In [25]:
df.shape

(500, 9)

In [27]:
df[4:90]

,Date,City,Temperature_C,Humidity_%,WindSpeed_kmh,Rainfall_mm,Pressure_hPa,Weather_Condition,UV_Index
4,2025-01-06,Lagos,23.7,87,28.8,56.8,1026,Windy,4
5,2025-01-07,Port Harcourt,32.4,52,12.7,3.1,1002,Rainy,4
6,2025-01-08,Abuja,35.1,51,10.8,65.0,993,Windy,9
7,2025-01-09,Abuja,19.4,66,3.6,104.0,987,Cloudy,8
8,2025-01-10,Port Harcourt,35.0,69,18.8,45.7,1032,Windy,9
...,...,...,...,...,...,...,...,...,...
85,2025-03-28,Port Harcourt,29.1,43,15.9,27.9,1013,Stormy,10
86,2025-03-29,Kano,25.6,70,11.4,7.7,999,Cloudy,9
87,2025-03-30,Kano,33.5,93,24.9,32.2,990,Cloudy,4
88,2025-03-31,Abuja,26.3,97,21.9,85.1,980,Stormy,1
89,2025-04-01,Port Harcourt,28.2,77,11.6,42.4,1023,Sunny,10

In [28]:
df.columns

Index(['Date', 'City', 'Temperature_C', 'Humidity_%', 'WindSpeed_kmh',
       'Rainfall_mm', 'Pressure_hPa', 'Weather_Condition', 'UV_Index'],
      dtype='str')

In [29]:
df.index

RangeIndex(start=0, stop=500, step=1)

In [30]:
df.dtypes

Date                     str
City                     str
Temperature_C        float64
Humidity_%             int64
WindSpeed_kmh        float64
Rainfall_mm          float64
Pressure_hPa           int64
Weather_Condition        str
UV_Index               int64
dtype: object

In [31]:
df[['Date','Weather_Condition']]

           Date Weather_Condition
0    2025-01-02             Rainy
1    2025-01-03             Sunny
2    2025-01-04            Stormy
3    2025-01-05            Cloudy
4    2025-01-06             Windy
..          ...               ...
495  2026-05-12            Stormy
496  2026-05-13             Windy
497  2026-05-14             Windy
498  2026-05-15             Windy
499  2026-05-16             Sunny

[500 rows x 2 columns]

In [32]:
df.Temperature_C

0      35.9
1      27.0
2      18.6
3      27.7
4      23.7
       ...
495    33.9
496    19.3
497    29.4
498    31.4
499    23.8
Name: Temperature_C, Length: 500, dtype: float64